## Load Library

In [1]:
import numpy as np

## The Basics

In [6]:
# Initializing the np array
a = np.array([1,2,3]) #1D Array with 3 elements
a
print(a)

[1 2 3]


In [9]:
b = np.array([[1,2,3], [4,5,6]]) #2D Array 
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
#Get dimension of np array
print(a.ndim)
print(b.ndim)

1
2


In [15]:
# Get shape : gives number of (rows, columns)
a.shape
b.shape

(2, 3)

In [16]:
# Get type 
b.dtype

dtype('int64')

In [18]:
# For specifying array to be of particular datatype initilize as:
c = np.array([[1,2,3], [4,5,6]], dtype ='int16')
c.dtype

dtype('int16')

In [20]:
# Get Size = gives number of elements
b.size

6

In [22]:
#Get to know how much memory respective array takes up
b.itemsize

8